### ISSUE TITLE
你真的挺菜的

### ISSUE THREAD

**Issue by Woolseyyy** [JourneyofRock/list#4]
这么点东西要人肉那么久 你真的有点菜啊
把我的用户名放到百度里搜一搜 看到csdn 然后看了看我的个人资料
这么点事居然花了一天

**Comment by guodong** [comment]
那2张已经用上了，还需要3张，尽量能周末前给我，我还得排版，谢了哈

**Comment by Woolseyyy** [comment]
@guodong 老哥挺强啊 比赛一个接着一个的

**Comment by guodong** [comment]
@Woolseyyy 😄学校比赛嘛，只要报名就有“报名成功奖”
